title:              Dhiaeddine's Blog
email:              dhiaeddine.gharsallah@gmail.com
description:        Dhiaeddine's Blog
author:             Dhiaeddine Gharsallah
# baseurl:            "/"
url:                "https://dgharsallah.github.io"

# Social Profiles
twitter_username:   d_gharsallah
github_username:    dgharsallah
facebook_username:  dgharsallah
linkedin_username: dgharsallah

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
